name: "Decompress alpine image"

on: 
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  decompress_with_alpyne:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: alpine:latest
            dir_name: IMG_alpine_latest
          - image_name: redis:latest
            dir_name: IMG_redis_latest
          - image_name: python:3.14-slim
            dir_name: IMG_python_3.14-slim
    runs-on: ubuntu-22.04
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Check docker
        shell: bash
        run: |
          docker ps
      
      - name: Download and install tree
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y tree
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      
      - name: Go mod tidy
        working-directory: ./go
        run: go mod tidy
      
      - name: Build go binaries
        working-directory: ./go
        shell: bash
        run: GOOS='linux' GOARCH='amd64' CGO_ENABLED=0 go build -o alpyne ./cmd/main.go
      
      - name: Add execute permission
        shell: bash
        run: |
          ls -lh
          chmod +x ./go/alpyne
      
      - name: Pull ${{ matrix.image_name }}
        shell: bash
        run: docker pull ${{ matrix.image_name }}
      
      - name: Decompress ${{ matrix.image_name }}
        shell: bash
        run: ./go/alpyne -i ${{ matrix.image_name }} -k && tree -L 2 ${{ matrix.dir_name }}
