name: "Decompress alpine image"
on: 
  workflow_dispatch:
jobs:
  pull_alpine:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: check_docker
        shell: bash
        run: |
          docker ps
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: build
        shell: bash
        run: |
          GOOS='linux' GOARCH='amd64' CGO_ENABLED=0 go build -o alpyne go/cmd/main.go
      - name: verify_build
        shell: bash
        run: |
          ls -lh
          chmod +x alpyne
      - name: pull_alpine_image
        shell: bash
        run: |
          docker pull alpine:latest
      - name: decompress_with_alpyne
        shell: bash
        run: |
          ./alpyne -i alpine:latest -k
          ls -lh
          
