name: "Decompress alpine image"

on: 
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  decompress_with_alpyne:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: check_docker
        shell: bash
        run: |
          docker ps
      - name: Download and install tree
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y tree
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Go mod tidy
        working-directory: ./go
        run: go mod tidy
      - name: build
        working-directory: ./go
        shell: bash
        run: |
          GOOS='linux' GOARCH='amd64' CGO_ENABLED=0 go build -o alpyne ./cmd/main.go
      - name: Add execute permission
        shell: bash
        run: |
          ls -lh
          chmod +x ./go/alpyne
      - name: Pull alpine image
        shell: bash
        run: |
          docker pull alpine:latest
      - name: Decompress alpine
        shell: bash
        run: |
          ./go/alpyne -i alpine:latest -k
          tree IMG_alpine_latest -L 2
      - name: Pull redis image
        shell: bash
        run: |
          docker pull redis:latest
      - name: Decompress redis
        shell: bash
        run: |
          ./go/alpyne -i redis:latest -k
          tree IMG_redis_latest -L 2
          
